general:
  label: 基本设置
  items:
    home_title:
      name: home_title
      label: 标签名
      type: text
      placeholder: '用于浏览器标签显示'
    home_ico:
      name: home_ico
      label: ico
      type: attachment
      placeholder: "用于浏览器ico显示"
company_info:
  label: 公司信息
  items:
    company_name:
      name: company_name
      label: 公司名称
      type: text
      placeholder: '填写公司名称'
    company_phone:
      name: company_phone
      label: 公司电话
      type: text
      placeholder: '填写公司名称'
    company_address:
      name: company_address
      label: 公司地址
      type: text
      placeholder: '填写公司地址'
    company_email:
      name: company_email
      label: 公司邮箱
      type: text
      placeholder: '填写公司邮箱'
    company_introduction:
      name: company_introduction
      label: 公司简介
      type: text
      placeholder: '填写公司简介'
    Icp:
      name: Icp
      label: 'ICP 备案号'
      type: text
      placeholder: '填入 ICP 备案号，没有则不填. '
    QR_code_official_account:
      name: QR_code_official_account
      label: '公众号二维码'
      type: attachment
      placeholder: '公众号二维码，不填不显示'
epoch_advance:
  label: '核心优势'
  items:
    epoch_advance_content:
      name: 'epoch_advance_content'
      label: '核心优势'
      type: text
      placeholder: '请简要描述核心优势'
    epoch_advance_title1:
      name: 'epoch_advance_title1'
      label: '核心优势1'
      type: text
      placeholder: '请填写核心优势1标题'
    epoch_advance_content1:
      name: 'epoch_advance_content1'
      label: '核心优势1内容'
      type: text
      placeholder: '请填写核心优势1内容'
    epoch_advance_title2:
      name: 'epoch_advance_title2'
      label: '核心优势2'
      type: text
      placeholder: '请填写核心优势2标题'
    epoch_advance_content2:
      name: 'epoch_advance_content2'
      label: '核心优势2内容'
      type: text
      placeholder: '请填写核心优势2内容'
    epoch_advance_title3:
      name: 'epoch_advance_title3'
      label: '核心优势3'
      type: text
      placeholder: '请填写核心优势3标题'
    epoch_advance_content3:
      name: 'epoch_advance_content3'
      label: '核心优势3内容'
      type: text
      placeholder: '请填写核心优势3内容'
    epoch_advance_title4:
      name: 'epoch_advance_title4'
      label: '核心优势4'
      type: text
      placeholder: '请填写核心优势4标题'
    epoch_advance_content4:
      name: 'epoch_advance_content4'
      label: '核心优势4内容'
      type: text
      placeholder: '请填写核心优势4内容'
    epoch_advance_title5:
      name: 'epoch_advance_title5'
      label: '核心优势5'
      type: text
      placeholder: '请填写核心优势5标题'
    epoch_advance_content5:
      name: 'epoch_advance_content5'
      label: '核心优势5内容'
      type: text
      placeholder: '请填写核心优势5内容'
    epoch_advance_title6:
      name: 'epoch_advance_title6'
      label: '核心优势6'
      type: text
      placeholder: '请填写核心优势6标题'
    epoch_advance_content6:
      name: 'epoch_advance_content6'
      label: '核心优势6内容'
      type: text
      placeholder: '请填写核心优势6内容'
product_introduction:
  label: '产品介绍'
  items:
    product1:
      name: 'product1'
      label: '新材料'
      type: attachment
    product2:
      name: 'product2'
      label: '新材料'
      type: attachment
    product3:
      name: 'product3'
      label: '新材料'
      type: attachment
    product4:
      name: 'product4'
      label: '通信设备'
      type: attachment
    product5:
      name: 'product5'
      label: '通信设备'
      type: attachment
    product6:
      name: 'product6'
      label: '通信设备'
      type: attachment
    product7:
      name: 'product7'
      label: '新能源'
      type: attachment
    product8:
      name: 'product8'
      label: '新能源'
      type: attachment
    product9:
      name: 'product9'
      label: '新能源'
      type: attachment



