apiVersion: epoch-v1
kind: Setting
spec:
  label: 样式
  forms:
    - group: style
      label: 样式
      formSchema:
          name: background_color
          type: color
          label: 背景颜色
          default: '#2474b5'
          placeholder: '网站主题色'
