apiVersion: epoch-v1
kind: Setting
metadata:
  label: epoch-theme
spec:
  label: 样式
  forms:
    - group: style
      label: 样式
      formSchema:
        - $formkit: color
          name: background_color
          label: 背景颜色
          value: "#f2f2f2"
